命令稿啟動於 2016年04月30日 (週六) 16時44分13秒
]0;csiebear@csiebear-virtual-machine: ~/lexercsiebear@csiebear-virtual-machine:~/lexer$ cat lexc[Ker.l
/*
The Lex structure
definition ＆rules ＆user code

definition
%%//separate by this
rules
%%
user code

*/
%{
	int num_line=1;
%}
Keywords int|char|float|double|return|if|else|while|break|for|print
Number [0-9]+
Identifier [a-zA-Z_][a-zA-Z0-9_]*
Operators \+|\-|\=|\*|\/|\!=|\<|\>|\<=|\>=
Special [{|}|(|)|;|,]
Char [.|\t]
Error [~] 
%%
\n {num_line++;
	printf("Line %d\n",num_line);
}
{Char} 
{Keywords} {
	printf("	<Keyword>		%s\n",yytext);
}

{Number} {
	printf("	<Number>		%s\n",yytext );
}
{Identifier} {
	printf("	<Identifier>		%s\n",yytext);
}
{Operators} {
	printf("	<Operator>		%s\n",yytext);
}
{Special} {
	printf("	<Special Symbol>	%s\n",yytext);
}
{Error} {
	printf("	<Error>			%s\n",yytext);
}
%%
main()
{
	printf("Line 1\n");
	yylex();
	return 0;
}
]0;csiebear@csiebear-virtual-machine: ~/lexercsiebear@csiebear-virtual-machine:~/lexer$ flex lexer.l
]0;csiebear@csiebear-virtual-machine: ~/lexercsiebear@csiebear-virtual-machine:~/lexer$ gcc lex.yy.c -ll
]0;csiebear@csiebear-virtual-machine: ~/lexercsiebear@csiebear-virtual-machine:~/lexer$ ./a.out <main.,[Kcpp
Line 1
	<Keyword>		int
 	<Identifier>		main
	<Special Symbol>	(
	<Special Symbol>	)
Line 2
	<Special Symbol>	{
Line 3
	<Keyword>		int
 	<Identifier>		i1
 	<Operator>		=
	<Number>		3
	<Special Symbol>	;
Line 4
	<Keyword>		if
	<Special Symbol>	(
	<Special Symbol>	)
	<Error>			~
Line 5
	<Special Symbol>	}
Line 6
]0;csiebear@csiebear-virtual-machine: ~/lexercsiebear@csiebear-virtual-machine:~/lexer$ 
命令稿已於 2016年04月30日 (週六) 16時44分58秒
 完成